name: gen-docs
run-name: Generate and publish docs
on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./
          recurse: true
          output_dir: ./doc
          front_page: README.md
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc